import { siteUrl } from './seo';

export const navigationItems = [
  { position: 1, name: "Acasă", url: siteUrl },
  { position: 2, name: "Articole", url: `${siteUrl}/articole` },
  { position: 3, name: "Omul care se reglează prin risc", url: `${siteUrl}/articole/unu` },
  { position: 4, name: "A fost odată un om ...", url: `${siteUrl}/articole/doi` },
  { position: 5, name: "Felul în care am ajuns să înțeleg adaptarea umană", url: `${siteUrl}/articole/trei` },
  { position: 6, name: "Manifest pentru învățarea minții si a corpului", url: `${siteUrl}/articole/patru` },
  { position: 7, name: "Consultanță comportamentală defensivă", url: `${siteUrl}/articole/cinci` },
  { position: 8, name: "Comportamentele care ne țin împreună (până nu ne mai țin)", url: `${siteUrl}/articole/sase` },
  { position: 9, name: "Nodul cel mai dureros din relații", url: `${siteUrl}/articole/sapte` },
  { position: 10, name: "Funcția din spatele comportamentului", url: `${siteUrl}/articole/opt` },
  { position: 11, name: "De ce stau oamenii in relații", url: `${siteUrl}/articole/noua` },
  { position: 12, name: "Costul biologic", url: `${siteUrl}/articole/zece` },
  { position: 13, name: "După despărțire", url: `${siteUrl}/articole/unspe` },
  { position: 14, name: "Influența mediului familial cu alcoolism asupra adultului: o perspectivă comportamentală și biologică", url: `${siteUrl}/articole/doispe` },
  { position: 15, name: "Moduri diferite prin care oamenii privesc realitatea interpersonală", url: `${siteUrl}/articole/treispe` },
  { position: 16, name: "Dinamica dintre stabilitatea funcțională si stabilitatea emoțională în cuplu", url: `${siteUrl}/articole/paispe` },
  { position: 17, name: "Dinamica unui cuplu în care ambii parteneri caută stabilitate funcțională", url: `${siteUrl}/articole/cinspe` },
  { position: 18, name: "Dinamica unui cuplu în care ambii parteneri caută stabilitate emoțională", url: `${siteUrl}/articole/saispe` },
  { position: 19, name: "Alte tipuri de relație", url: `${siteUrl}/articole/saptespe` },
  { position: 20, name: "Starea biologică, gândul și conflictul uman - explicație pe înțelesul oamenilor", url: `${siteUrl}/articole/opspe` },
  { position: 21, name: "De ce unii oameni nu te lasă în pace - ghid de prevenție (pe înțelesul oricui)", url: `${siteUrl}/articole/nouaspe` },
  { position: 22, name: "Mecanismul comportamentului de hărțuire și agresiune", url: `${siteUrl}/articole/douazeci` },
  { position: 23, name: "Starea biologică și modul în care ne influențează viața", url: `${siteUrl}/articole/douașunu` },
  { position: 24, name: "Nu alegi după chef. Alegi după efect biologic", url: `${siteUrl}/articole/douașdoi` },
  { position: 25, name: "Imaginea noastră despre oameni", url: `${siteUrl}/articole/douaștrei` },
  { position: 26, name: "Conștientizarea proiecției: ce se întâmplă când înțelegem că nu interacționăm cu persoana reală, ci cu imaginea noastră despre ea", url: `${siteUrl}/articole/douașpatru` },
  { position: 27, name: "De ce o relație bună se simte în corp, nu doar în inimă", url: `${siteUrl}/articole/douașcinci` },
  { position: 28, name: "De ce oamenii nu fac ceea ce înțeleg - rolul stării biologice în decizie și comportament", url: `${siteUrl}/articole/douașsase` },
  { position: 29, name: "De ce o persoană te alege, iar apoi se desparte - explicație biologică și psihică, pe înțelesul tuturor", url: `${siteUrl}/articole/douașsapte` },
  { position: 30, name: "Cum se aleg oamenii (Modelul ISAC CONSULT)", url: `${siteUrl}/articole/douașopt` },
  { position: 31, name: "De ce omul înțelege abia după ce face, nu înainte", url: `${siteUrl}/articole/douașnoua` },
  { position: 32, name: "Comportamentul nou creează omul nou", url: `${siteUrl}/articole/treizeci` },
  { position: 33, name: "Pe românește: ce face psihologul și ce fac eu", url: `${siteUrl}/articole/treizeciunu` },
  { position: 34, name: 'Ce înseamnă de fapt „îti pasă"', url: `${siteUrl}/articole/treizecidoi` },
  { position: 35, name: 'De ce creierul preferă impactul emoțional în locul liniștii - pacea psihică versus certitudinea biologică', url: `${siteUrl}/articole/treizecitrei` },
  { position: 36, name: 'Certitudinea din punct de vedere biologic — de ce creierul caută reacția, nu liniștea', url: `${siteUrl}/articole/treizecipatru` },
  { position: 37, name: 'Intenția aparține celui care acționează, consecința aparține celui care trăiește acțiunea', url: `${siteUrl}/articole/treizecicinci` },
  { position: 38, name: 'De ce creierul trebuie reglat biologic înainte de a fi înțeles psihologic', url: `${siteUrl}/articole/treizecisase` },    
  { position: 39, name: 'De ce omul te înțelege abia dupa ce relația s-a terminat', url: `${siteUrl}/articole/treizecisapte` },
  { position: 39, name: 'De ce oamenii reacționeaza la starea noastră și nu la intențiile noastre', url: `${siteUrl}/articole/treizeciopt` },
  { position: 40, name: 'De ce unele relații se mențin prin conflict — reglarea biologică interpersonală', url: `${siteUrl}/articole/treizecinoua` },
  { position: 41, name: 'Ce face creierul când apare o altă persoană', url: `${siteUrl}/articole/patruzeci` },
  { position: 42, name: 'Cum se construiește stabilitatea bio-psiho-socială', url: `${siteUrl}/articole/patruzeciunu` },
  { position: 42, name: 'De ce problemele nu se rezolvă prin gândire', url: `${siteUrl}/articole/patruzecidoi` },
  { position: 43, name: 'Cum și de ce corpul produce hormoni ai stresului și cum apare anxietatea', url: `${siteUrl}/articole/patruzecitrei` },
  { position: 44, name: 'De ce nu trebuie să așteptăm viitorul și cum se construiește el prin acțiunile noastre', url: `${siteUrl}/articole/patruzecipatru` },
  { position: 45, name: 'De ce oamenii nu cred explicațille pe care le primesc', url: `${siteUrl}/articole/patruzecicinci` },
  { position: 46, name: 'Minciuna la persoanele cu trăsaturi psihopatice și narcisice', url: `${siteUrl}/articole/patruzecisase` },
  { position: 47, name: 'Negarea sociala - mecanismul prin care comunitățile refuză să accepte nedreptatea produsă în interiorul lor', url: `${siteUrl}/articole/patruzecisapte` },
  { position: 48, name: 'Anxietatea anticipativă - teama produsă de ceea ce credem că se va întâmpla', url: `${siteUrl}/articole/patruzeciopt` },
  { position: 49, name: 'Diferența dintre ceea ce văd oamenii și ceea ce vede o persoană orientată spre consecințe', url: `${siteUrl}/articole/patruzecinoua` },
  { position: 50, name: 'Minciuna la personalitățile narcisice și antisociale', url: `${siteUrl}/articole/cinzeci` },
  { position: 51, name: 'Diferențele de comportament dintre personalitatea narcisică și personalitatea antisocială - exemple din viața de zi cu zi', url: `${siteUrl}/articole/cinzeciunu` },
  { position: 52, name: 'Tipologii umane', url: `${siteUrl}/articole/cinzecidoi` },
  { position: 53, name: 'Narcisismul', url: `${siteUrl}/articole/cinzecitrei` },
  { position: 54, name: 'Ce este Stresul', url: `${siteUrl}/articole/cinzecipatru` },
  { position: 55, name: 'Stresul - explicație chimică', url: `${siteUrl}/articole/cinzecicinci` },
  { position: 56, name: 'Adaptarea la mediu', url: `${siteUrl}/articole/cinzecisase` },
  { position: 57, name: 'Percepția realității', url: `${siteUrl}/articole/cinzecisapte` },
  { position: 58, name: 'Când corpul nu descarcă energie, mintea descarcă pe oameni', url: `${siteUrl}/articole/cinzeciopt` },
  { position: 59, name: 'De ce este importantă poziția socială și cum ajunge omul să nu mai depindă de validarea celorlalți', url: `${siteUrl}/articole/cinzecinoua` },
  { position: 60, name: 'Acceptare vs înțelegere', url: `${siteUrl}/articole/saizeci` },
  { position: 61, name: 'Victima reală vs victima psihologică vs comportamentul învățat care aduce beneficii', url: `${siteUrl}/articole/saizeciunu` },
  { position: 62, name: 'Cum folosesc persoanele cu trăsături narcisice și psihopatice comportamentul de victimă', url: `${siteUrl}/articole/saizecidoi` },
  { position: 63, name: 'Persoane puternice fără a fi agresoare vs persoane fără putere, dar agresoare', url: `${siteUrl}/articole/saizecitrei` },
  { position: 64, name: 'Minciuna și moralitatea', url: `${siteUrl}/articole/saizecipatru` },
  { position: 65, name: 'Minciuna, gândirea și comportamentul în tiparele antisociale și diferența față de observatorul lucid', url: `${siteUrl}/articole/saizecicinci` },
  { position: 66, name: 'Cum se formează comportamentele orientate spre viitor', url: `${siteUrl}/articole/saizecisase` },
  { position: 67, name: 'De ce nu toți copiii fără plasă de siguranță dezvoltă gândirea anticipativă', url: `${siteUrl}/articole/saizecisapte` },
  { position: 68, name: 'Oamenii nu aleg doar binele. Aleg ceea ce pot gestiona.', url: `${siteUrl}/articole/saizeciopt` },
  { position: 69, name: 'Comportamentul nou și cum poate deveni stabil', url: `${siteUrl}/articole/saizecinoua` },
  { position: 70, name: 'Motivul te minte, funcția nu', url: `${siteUrl}/articole/saptezeci` },
  { position: 71, name: 'Comportamentele au mai multe funcții', url: `${siteUrl}/articole/saptezeciunu` },
  { position: 72, name: 'Comportamentul se repetă din cauza funcției, nu a motivului sau a scopului', url: `${siteUrl}/articole/saptezecidoi` },
  { position: 73, name: 'Îți propui ceva și începi, dar continui doar dacă îți iese ceva din asta', url: `${siteUrl}/articole/saptezecitrei` },
  { position: 74, name: 'Relațiile văzute prin gândirea în variante', url: `${siteUrl}/articole/saptezecipatru` },
  { position: 75, name: 'Cum îți creezi realitatea', url: `${siteUrl}/articole/saptezecicinci` },
  { position: 76, name: 'Niveluri diferite în conflict și dificultatea rezolvării (bio-psiho-social)', url: `${siteUrl}/articole/saptezecisase` },
  { position: 77, name: 'Aplicarea modelului bio-psiho-social în comunicare și luarea deciziilor', url: `${siteUrl}/articole/saptezecisapte` },
  { position: 78, name: 'Contextul similar activează comportamentele deja învățate', url: `${siteUrl}/articole/saptezeciopt` },
  { position: 79, name: 'Funcționează vs. e bine', url: `${siteUrl}/articole/saptezecinoua` },
  { position: 80, name: 'Comportamentele care apar după perioada de inceput a unei relații', url: `${siteUrl}/articole/optzeci` },
  { position: 81, name: 'La început alegi cine ești. După apare cine ești invățat să fii', url: `${siteUrl}/articole/optzeciunu` },
];

export const siteNavScript = {
  "@context": "https://schema.org",
  "@type": "ItemList",
  itemListElement: navigationItems.map(item => ({
    "@type": "SiteNavigationElement",
    position: item.position,
    name: item.name,
    url: item.url,
  })),
};
