import { siteUrl } from './seo';

export const navigationItems = [
  { position: 1, name: "Acasă", url: siteUrl },
  { position: 2, name: "Articole", url: `${siteUrl}/articole` },
  { position: 3, name: "Omul care se reglează prin risc", url: `${siteUrl}/articole/unu` },
  { position: 4, name: "A fost odată un om ...", url: `${siteUrl}/articole/doi` },
  { position: 5, name: "Felul în care am ajuns să înțeleg adaptarea umană", url: `${siteUrl}/articole/trei` },
  { position: 6, name: "Manifest pentru învățarea minții si a corpului", url: `${siteUrl}/articole/patru` },
  { position: 7, name: "Consultanță comportamentală defensivă", url: `${siteUrl}/articole/cinci` },
  { position: 8, name: "Comportamentele care ne țin împreună (până nu ne mai țin)", url: `${siteUrl}/articole/sase` },
  { position: 9, name: "Nodul cel mai dureros din relații", url: `${siteUrl}/articole/sapte` },
  { position: 10, name: "Funcția din spatele comportamentului", url: `${siteUrl}/articole/opt` },
  { position: 11, name: "De ce stau oamenii in relații", url: `${siteUrl}/articole/noua` },
  { position: 12, name: "Costul biologic", url: `${siteUrl}/articole/zece` },
  { position: 13, name: "După despărțire", url: `${siteUrl}/articole/unspe` },
  { position: 14, name: "Influența mediului familial cu alcoolism asupra adultului: o perspectivă comportamentală și biologică", url: `${siteUrl}/articole/doispe` },
  { position: 15, name: "Moduri diferite prin care oamenii privesc realitatea interpersonală", url: `${siteUrl}/articole/treispe` },
  { position: 16, name: "Dinamica dintre stabilitatea funcțională si stabilitatea emoțională în cuplu", url: `${siteUrl}/articole/paispe` },
  { position: 17, name: "Dinamica unui cuplu în care ambii parteneri caută stabilitate funcțională", url: `${siteUrl}/articole/cinspe` },
  { position: 18, name: "Dinamica unui cuplu în care ambii parteneri caută stabilitate emoțională", url: `${siteUrl}/articole/saispe` },
  { position: 19, name: "Alte tipuri de relație", url: `${siteUrl}/articole/saptespe` },
  { position: 20, name: "Starea biologică, gândul și conflictul uman - explicație pe înțelesul oamenilor", url: `${siteUrl}/articole/opspe` },
  { position: 21, name: "De ce unii oameni nu te lasă în pace - ghid de prevenție (pe înțelesul oricui)", url: `${siteUrl}/articole/nouaspe` },
  { position: 22, name: "Mecanismul comportamentului de hărțuire și agresiune", url: `${siteUrl}/articole/douazeci` },
  { position: 23, name: "Starea biologică și modul în care ne influențează viața", url: `${siteUrl}/articole/douașunu` },
  { position: 24, name: "Nu alegi după chef. Alegi după efect biologic", url: `${siteUrl}/articole/douașdoi` },
  { position: 25, name: "Imaginea noastră despre oameni", url: `${siteUrl}/articole/douaștrei` },
  { position: 26, name: "Conștientizarea proiecției: ce se întâmplă când înțelegem că nu interacționăm cu persoana reală, ci cu imaginea noastră despre ea", url: `${siteUrl}/articole/douașpatru` },
  { position: 27, name: "De ce o relație bună se simte în corp, nu doar în inimă", url: `${siteUrl}/articole/douașcinci` },
  { position: 28, name: "De ce oamenii nu fac ceea ce înțeleg - rolul stării biologice în decizie și comportament", url: `${siteUrl}/articole/douașsase` },
  { position: 29, name: "De ce o persoană te alege, iar apoi se desparte - explicație biologică si psihică, pe înțelesul tuturor", url: `${siteUrl}/articole/douașsapte` },
  { position: 30, name: "Cum se aleg oamenii (Modelul ISAC CONSULT)", url: `${siteUrl}/articole/douașopt` },
  { position: 31, name: "De ce omul ințelege abia după ce face, nu înainte", url: `${siteUrl}/articole/douașnoua` },
  { position: 32, name: "Comportamentul nou creează omul nou", url: `${siteUrl}/articole/treizeci` },
  { position: 33, name: "Pe românește: ce face psihologul și ce fac eu", url: `${siteUrl}/articole/treizeciunu` },
];

export const siteNavScript = {
  "@context": "https://schema.org",
  "@type": "ItemList",
  itemListElement: navigationItems.map(item => ({
    "@type": "SiteNavigationElement",
    position: item.position,
    name: item.name,
    url: item.url,
  })),
};
